### ISSUE TITLE
Make it possible to wrap one element in another

### ISSUE THREAD

**Issue by jplew** [dmbaturin/soupault#32]
Hello, I have the following widgets in my `soupault.conf`:

```toml
[widgets.blog-container-before]
  widget = "insert_html"
  html = '<div class="prose dark:prose-light lg:prose-lg prose-lime mx-auto">'
  selector = "#content-selector"
  parse = true
  section = "blog"
  action = "insert_before"

[widgets.blog-container-after]
  widget = "insert_html"
  html = '</div>'
  selector = "#content-selector"
  parse = true
  section = "blog"
  action = "insert_after"
```

My intention is to turn this:

```html
<div id="content-selector"></div>
```

...into this:

```html
<div class="prose dark:prose-light lg:prose-lg prose-lime mx-auto">
    <div id="content-selector"></div>
</div>
```

Unfortunately, after running `soupault` I wind up with this:

```html
<div class="prose dark:prose-light lg:prose-lg prose-lime mx-auto"></div>
    <div id="content-selector"></div>
</div>
```

The "before" html is being automatically closed with a `</div>` on the same line. I've witnessed this behaviour in my IDE before, where typing `<div>` automatically generates the corresponding `</div>`, but I'm not sure where in the build process this  is occurring. Is it even possible to insert the first part of a div tag?

Alternatively, do you have a better suggestion on how to achieve my goal? The idea is that blog posts use the same template as the rest of my pages, the only exception being they need a wrapping div to constrain their width. I know I can create an alternate template, but I prefer to achieve it with a single template if possible. Thanks in advance!

**Comment by jplew** [comment]
It appears as though the HTML validation step takes place here: https://github.com/dmbaturin/soupault/blob/master/src/html_utils.ml#L14

Markup.ml cleans up all the "bad" HTML. 

However, what about my use case where I want to insert bad HTML on purpose, in order to surround a selector? Do you think it's possible to introduce a boolean flag on the `include` and `insert_html` widgets like `accept_bad_html`. When false, `parse_html` would bypass `Markup.signals` and output the snippet as-is.

This would allow a user to surround their content with "before" HTML like this:

```
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
      <div class="relative py-16 overflow-hidden">
        <div class="relative mt-6 px-4 sm:px-6 lg:px-8">
```

And "after" HTML like this:

```
        </div>
      </div>
    </div>
```

This is currently not possible due to `Markup.signals` adding ``End_element`s everywhere. Please let me know your thoughts. 

@aantron I'd be interested to hear your opinion too. Thanks!

**Comment by aantron** [comment]
At first glance, if I understood correctly, it looks like you need one widget or one template, so that it can have balanced start and end tags to wrap your content.

On the Markup.ml side, it is possible to modify it to be able to either emit only tokens, or suppress error recovery. However, if this can be solved using another way that is more natural (with a proper template), I would prefer that, because Markup.ml currently implements the HTML5 spec for parsing HTML documents and fragments, which *requires* the behavior you are seeing.

To get really pedantic in light of the spec, the usage of the two widgets you have right now is kind of misleading when it comes to terminology :P

> ```toml
> [widgets.blog-container-after]
>   widget = "insert_html"
>   html = '</div>'
>   selector = "#content-selector"
>   parse = true
>   section = "blog"
>   action = "insert_after"
> ```

...because you are not trying to insert HTML (`"insert_html"`), but some HTML *tokens*, and you don't want to interpret `'</div>`" as HTML (`html = '</div>'`), but only as a token, because interpreting it as HTML according to the *language*'s current spec requires it to be dropped by the error recovery rules in that spec (because there is no starting tag). To do this truly with *HTML*, you'd need a template or widget with at least roughly balanced tags, as I mentioned at the start of this comment.

I'd like to hear @dmbaturin's opinion on how this should be done in Soupault.

**Comment by jplew** [comment]
Thanks Anton for chiming in. I can appreciate the value of preserving the proper HTML terminology and sticking to the spec.

I'm not attached to any particular solution, but I think the template system could better serve users by offering more options for code reuse. Take this scenario:

![image](https://user-images.githubusercontent.com/462836/116801061-03736a80-ab24-11eb-8549-bdf24cbf6dc1.png)

This is my `templates/blog.html` vs. my `templates/home.html`. I end up duplicating markup in each one, which is hard to maintain, and would prefer a more DRY alternative. I find this hard to achieve with the built-in widgets. 

One alternate solution is to introduce a "pre-content-injection" hook:

```toml
[widgets.replace-content-wrapper]
  widget = "insert_html"
  html = """
  <div class="prose dark:prose-light lg:prose-lg prose-lime mx-auto">
    <div id="content-selector"></div>
  </div>
  """
  selector = "#content-selector"
  parse = true
  section = "blog"
  action = "replace_element"
  before = "content-insertion"
```  
  
Lastly, another option might be to provide a `{{content}}` built-in field:

```toml
[widgets.blog-content-insertion]
  widget = "insert_html"
  html = """
  <div class="prose dark:prose-light lg:prose-lg prose-lime mx-auto">
    <div id="content-selector">{{content}}</div>
  </div>
  """
  selector = "#content-selector"
  parse = true
  section = blog
  action = "replace_element"
```  

Then again, this whole thing might be an edge case, in which case you can disregard my whining. :)

**Comment by dmbaturin** [comment]
Sorry for late reply. @aantron got to it before me and explained it better than I could—indeed, right now that widget cannot inject tokens, and I'm pretty sure it shouldn't do that since the HTML validness is a good invariant to preserve.

Regarding a built-in template field, I'd like to keep template rendering and element tree manipulation separate concepts.

Regarding your use case specifically: I think it's definitely valid, and not even that uncommon. I was thinking of adding a `wrap` widget that might look like this:

```toml
[widgets.wrap-posts]
  widget = "wrap"
  selector = "div.post"
  select_all = true
  wrapper = """ <div class="post-wrapper"> """
  wrapper_selector = "div"
```
Sadly this needs the awkward `wrapper_selector` option for wrappers like `<div class="foo"> <div class="bar"> </div> </div>` if you want to insert in the inner element. I think I have an idea how to make this seamless in _most_ cases: if the wrapper has a single top level element _and_ that element has no children, then just wrap in the top level element. Else raise an error and ask the user to specify the `wrapper_selector` by hand.

Maybe there can be a separate widget that uses a template instead.

Let me know what you think.

**Comment by jplew** [comment]
No worries, thanks for the support. 🙏 
A wrap widget sounds awesome. The `wrapper_selector` doesn't seem all that awkward either.

**Comment by dmbaturin** [comment]
If that design looks good to you, I'll try to make a prototype this week and let you know.

**Comment by dmbaturin** [comment]
I tested it with this config:

```toml
[widgets.wrap-main]
  widget = "wrap"
  wrapper = "<div class=\"main-wrapper\">"
  selector = "main"
```

The `wrap_all` option is `true` by default. You can omit the `wrapper_selector` option iff the wrapper has exactly one child element in it. If there's more than one element, you'll get an error that suggests what to do:

```
[ERROR] Could not process page site/reference-manual.md: the wrapper has more then one child element but the wrapper selector is not specified
```

**Comment by jplew** [comment]
Great, I'd love to take this widget for a spin. Do you plan on releasing a new binary or should I build from source?

**Comment by dmbaturin** [comment]
@jplew I definitely would like you to test this before I make an official release with it. If you don't have an opportunity to build from source now, I can make a test binary for you, just tell me which OS you want to test on.

**Comment by jplew** [comment]
Linux please. 👍

**Comment by dmbaturin** [comment]
@jplew Here you go: https://files.baturin.org/tmp/soupault-2.7.0-dev-f8fdac7bd

**Comment by jplew** [comment]
I tested it, it works great! In addition to your simple example, I was able to use the following widget to nest child divs:

```toml
[widgets.wrap-multiple]
  widget = "wrap"
  wrapper = """
  <div class=\"text-3xl\"> 
    <div class=\"font-bold\"> 
      <div class=\"text-red-200\" id=\"innermost-div\">
  """
  selector = "#wrap-me-up"
  wrapper_selector = "#innermost-div"
```

Turns this:
```html
    <div id="wrap-me-up">I'm a random div</div>
```

Into this:

```html
    <div class="text-3xl">
      <div class="font-bold">
        <div class="text-red-200" id="innermost-div">
          <div id="wrap-me-up">I'm a random div</div>
        </div>
      </div>
    </div>
```

Thanks for adding that feature so fast. This is exactly what I was hoping for. 

Not sure if you ever run into compatibility issues, but if you want help testing on Mac feel free to send me another binary.
